### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by pioto** [pioto/Unix-Uptime#13]
See: https://rt.cpan.org/Ticket/Display.html?id=102806

Note that Cygwin was done on #2...

---

Seems a fair number of people try to test this on Windows, judging from the CPAN Testers reports. So maybe just support it somehow. Maybe even just Cygwin could be a fair start...

But getting further would probably mean the name should change to Sys::Uptime... but that would require getting the rights to that namespace... http://search.cpan.org/dist/Sys-Uptime/

**Comment by plicease** [comment]
Cygwin is already supported.

**Comment by pioto** [comment]
@plicease yes.... as I noted above...

(I'm just porting over old notes from RT to Github)

**Comment by plicease** [comment]
Oh sorry lol I was reading the second paragraph "...Cygwin could be a fair start..."  nevermind!

**Comment by pioto** [comment]
# UNMAINTAINED

This code is something I haven't used in at least 6 years. I'm no longer
an active Perl coder, so I'm marking this repository as archived. If you're
interested in picking up this project, feel free to fork, and reach
out ot me to discuss handing over maintainership in CPAN, etc.
