### ISSUE TITLE
Support HP-UX

### ISSUE THREAD

**Issue by ironbishop** [pioto/Unix-Uptime#19]
11.11, 11.23, etc ..

**Comment by pioto** [comment]
I have no access to any such system, but patches are welcome.

**Comment by pioto** [comment]
# UNMAINTAINED

This code is something I haven't used in at least 6 years. I'm no longer
an active Perl coder, so I'm marking this repository as archived. If you're
interested in picking up this project, feel free to fork, and reach
out ot me to discuss handing over maintainership in CPAN, etc.
